version: "3.7"

services:
  mysql:
    image: mysql:8.0.41
    hostname: mysql
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: dbcartoes
      MYSQL_ROOT_PASSWORD: root

    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

  flyway:
    image: flyway/flyway:11.3.1
    container_name: flyway_mysql_cartoes
    command: -url=jdbc:mysql://mysql:3306/dbcartoes -user=root -password=root -connectRetries=120 migrate -X
    volumes:
      - ./src/main/resources/db/migration:/flyway/sql
    depends_on:
      mysql:
        condition: service_healthy



