quarkus:
  http:
    port: 8080
    root-path: /bank

  devservices:
    enabled: true
  datasource:
    db-kind: mysql
    jdbc:
      url: jdbc:mysql://localhost:3306/dbcartoes
    username: root
    password: root
  flyway:
    migrate-at-start: true
    baseline-on-migrate: true


app:
  api:
    key: "zdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6Ik"
